services:
  app:
    build: ./app
    container_name: flask-container
    command: python app.py
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost/orderscatalog
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: orderscatalog
