version: '3'

services:
  app:
    build:
      context: .
    links:
      - postgres://localhost
    volumes:
      - /usr/src/app/static
    env_file: .env
    ports:
      - 5000:5000

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderscatalog
      POSTGRES_HOST: localhost
    volumes:
      - /postgres-data:/var/lib/postgresql/dat
    ports:
      - "5432:5432"  